name: CI/CD to Hugging Face Space

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Run basic tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote Hugging Face Space
        env:
          DEPLOYHF: ${{ secrets.DEPLOYHF }}
        run: |
          git remote add space https://vel740:${DEPLOYHF}@huggingface.co/spaces/vel740/mlkonsumsilistrikv1.1
      - name: Push to Hugging Face Space
        run: |
          git push space main --force
