name: CI/CD to Hugging Face Space

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Run some tests
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add remote HuggingFace Space
        env:
          DEPLOYHF: ${{ secrets.DEPLOYHF }}
        run: |
          git remote add space https://user:${DEPLOYHF}@huggingface.co/spaces/vel740/dev-konsumsi-listrik
      - name: Push to HuggingFace Space
        env:
          DEPLOYHF: ${{ secrets.DEPLOYHF }}
        run: |
          git push --force space main
